export enum INPUT_TYPES {
    TEXT = 'text',
    NUMBER = 'number',
    DATE = 'date',
    TIME = 'time',
    MONTH = 'month',
    DROPDOWN = 'select',
    CHECKBOX = 'checkbox',
    RADIO = 'radio',
    TEXTAREA = 'textarea',
    FILE = 'file',
    PASSWORD = 'password',
    EMAIL = 'email',
    TEL = 'tel',
    URL = 'url',
    INFO = 'info',
    OBJECT = 'object',
    ARRAY = 'array',
    FUNCTION = 'function',
    SECTION = 'section',
    BOOLEAN = 'boolean',
}